CREATE TABLE "medicines" (
	"id" text PRIMARY KEY NOT NULL,
	"prescription_id" text NOT NULL,
	"medicine" text NOT NULL,
	"dosage" text NOT NULL,
	"form" text,
	"frequency" text,
	"duration" text,
	"route" text,
	"timing" text,
	"with_food" boolean DEFAULT false,
	"instructions" text,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "prescriptions" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"patient_name" text NOT NULL,
	"patient_age" text,
	"patient_gender" text,
	"patient_phone" text,
	"patient_address" text,
	"diagnosis" text NOT NULL,
	"chief_complaint" text,
	"history_of_present_illness" text,
	"physical_examination" text,
	"differential_diagnosis" text,
	"pulse_rate" text,
	"blood_pressure" text,
	"temperature" text,
	"respiratory_rate" text,
	"oxygen_saturation" text,
	"allergies" jsonb,
	"current_medications" jsonb,
	"past_medical_history" text,
	"family_history" text,
	"social_history" text,
	"instructions" text,
	"follow_up" text,
	"restrictions" text,
	"doctor_name" text NOT NULL,
	"doctor_license_number" text,
	"clinic_name" text,
	"clinic_address" text,
	"doctor_free" text,
	"prescription_date" timestamp with time zone DEFAULT now(),
	"prescription_number" text,
	"source" text,
	"status" varchar(20) DEFAULT 'active',
	"ai_confidence" text,
	"ai_model_used" text,
	"processing_time" integer,
	"raw_ai_response" jsonb,
	"created_at" timestamp with time zone DEFAULT now(),
	"updated_at" timestamp with time zone DEFAULT now()
);
