import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeInitializer } from "@/components/theme-initializer";
import { Providers } from "@/components/providers";
import { faIR } from "@clerk/localizations";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={faIR}>
      <ThemeProvider>
        <Providers>
          <html lang="fa" dir="rtl">
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              <ThemeInitializer />
              {children}
            </body>
          </html>
        </Providers>
      </ThemeProvider>
    </ClerkProvider>
  );
}
