// Constants and configuration for the enhanced prescription form

import { Heart, Brain, Activity, Scan, Radiation, Syringe } from "lucide-react";

// Dosage options
export const DOSAGE_OPTIONS = [
  { value: "250mg", label: "250 mg" },
  { value: "500mg", label: "500 mg" },
  { value: "750mg", label: "750 mg" },
  { value: "1000mg", label: "1000 mg" },
  { value: "5mg", label: "5 mg" },
  { value: "10mg", label: "10 mg" },
  { value: "20mg", label: "20 mg" },
  { value: "40mg", label: "40 mg" },
  { value: "50mcg", label: "50 mcg" },
  { value: "100mcg", label: "100 mcg" },
  { value: "5ml", label: "5 ml" },
  { value: "10ml", label: "10 ml" },
  { value: "custom", label: "Other (Custom)" },
];

// Import frequency and duration options from utility
import {
  getFrequencyOptions,
  getDurationOptions,
} from "@/lib/medicationTimingTranslations";

export const FREQUENCY_OPTIONS = getFrequencyOptions();
export const DURATION_OPTIONS = getDurationOptions();

// Physical exam categories
export const PHYSICAL_EXAM_CATEGORIES = [
  { id: "general", label: "General Examination", icon: "👤" },
  { id: "cardio", label: "Cardiovascular", icon: Heart },
  { id: "respiratory", label: "Respiratory", icon: Activity },
  { id: "neuro", label: "Neurological", icon: Brain },
  { id: "abdominal", label: "Abdominal", icon: Scan },
];

// System examination options with icons
export const SYSTEM_EXAM_OPTIONS = {
  cns: [
    { label: "Consciousness: Alert and oriented", icon: "👁️" },
    { label: "Consciousness: Drowsy", icon: "😴" },
    { label: "Consciousness: Confused", icon: "🤔" },
    { label: "Memory: Intact", icon: "🧠" },
    { label: "Memory: Impaired short-term", icon: "⏳" },
    { label: "Speech: Clear and fluent", icon: "💬" },
    { label: "Speech: Slurred", icon: "🗣️" },
    { label: "Cranial nerves: Intact", icon: "👁️" },
    { label: "Cranial nerves: Deficits present", icon: "⚠️" },
    { label: "Motor: Normal tone and power", icon: "💪" },
    { label: "Motor: Weakness present", icon: "🦽" },
    { label: "Motor: Hypertonia", icon: "🦾" },
    { label: "Motor: Hypotonia", icon: "🦿" },
    { label: "Sensory: Intact to all modalities", icon: "👐" },
    { label: "Sensory: Decreased sensation", icon: "✋" },
    { label: "Sensory: Paresthesia", icon: "🪡" },
    { label: "Reflexes: Normal", icon: "🦵" },
    { label: "Reflexes: Hyperreflexia", icon: "⚡" },
    { label: "Reflexes: Hyporeflexia", icon: "🔇" },
    { label: "Reflexes: Plantar flexor", icon: "🦶" },
    { label: "Reflexes: Plantar extensor", icon: "🚩" },
    { label: "Coordination: Normal", icon: "🎯" },
    { label: "Coordination: Ataxia present", icon: "🌀" },
    { label: "Gait: Normal", icon: "🚶" },
    { label: "Gait: Abnormal", icon: "🦽" },
    { label: "No focal neurological deficits", icon: "✅" },
  ],
  cardiovascular: [
    { label: "Heart sounds: S1, S2 normal", icon: "❤️" },
    { label: "Heart sounds: S3 present", icon: "💓" },
    { label: "Heart sounds: S4 present", icon: "💗" },
    { label: "Heart sounds: Murmur present", icon: "🫀" },
    { label: "Murmur: Systolic", icon: "📈" },
    { label: "Murmur: Diastolic", icon: "📉" },
    { label: "Jugular venous pressure: Normal", icon: "🫁" },
    { label: "Jugular venous pressure: Elevated", icon: "📊" },
    { label: "Peripheral pulses: All palpable", icon: "🫳" },
    { label: "Peripheral pulses: Diminished", icon: "🫴" },
    { label: "Peripheral pulses: Absent", icon: "❌" },
    { label: "Edema: None", icon: "🦵" },
    { label: "Edema: Pedal", icon: "👣" },
    { label: "Edema: Lower limb", icon: "🦿" },
    { label: "Edema: Generalized", icon: "🌊" },
    { label: "Cyanosis: Absent", icon: "👄" },
    { label: "Cyanosis: Peripheral", icon: "👣" },
    { label: "Cyanosis: Central", icon: "👁️" },
    { label: "Capillary refill: <2 seconds", icon: "⏱️" },
    { label: "Capillary refill: Delayed", icon: "⏳" },
    { label: "Blood pressure: Normal in all limbs", icon: "🩺" },
    { label: "Blood pressure: Difference between limbs", icon: "⚖️" },
    { label: "No signs of heart failure", icon: "✅" },
  ],
  respiratory: [
    { label: "Breath sounds: Vesicular", icon: "🫁" },
    { label: "Breath sounds: Bronchial", icon: "🌳" },
    { label: "Breath sounds: Diminished", icon: "🔇" },
    { label: "Breath sounds: Absent", icon: "❌" },
    { label: "Added sounds: None", icon: "✅" },
    { label: "Added sounds: Wheeze", icon: "🎵" },
    { label: "Added sounds: Rhonchi", icon: "🌀" },
    { label: "Added sounds: Crackles", icon: "✨" },
    { label: "Added sounds: Stridor", icon: "🎼" },
    { label: "Added sounds: Pleural rub", icon: "🔄" },
    { label: "Percussion: Resonant", icon: "🥁" },
    { label: "Percussion: Dull", icon: "🔇" },
    { label: "Percussion: Hyperresonant", icon: "📯" },
    { label: "Chest expansion: Symmetrical", icon: "⚖️" },
    { label: "Chest expansion: Asymmetrical", icon: "⚡" },
    { label: "Trachea: Central", icon: "🎯" },
    { label: "Trachea: Deviated", icon: "↔️" },
    { label: "Cough: Absent", icon: "✅" },
    { label: "Cough: Productive", icon: "🫧" },
    { label: "Cough: Non-productive", icon: "💨" },
    { label: "Sputum: Clear", icon: "💧" },
    { label: "Sputum: Purulent", icon: "🟡" },
    { label: "Sputum: Blood-stained", icon: "🩸" },
    { label: "Chest pain: Absent", icon: "✅" },
    { label: "Chest pain: Pleuritic", icon: "😖" },
    { label: "No respiratory distress", icon: "😌" },
  ],
  gastrointestinal: [
    { label: "Abdomen: Soft and non-tender", icon: "🫄" },
    { label: "Abdomen: Distended", icon: "🎈" },
    { label: "Abdomen: Rigid", icon: "🛡️" },
    { label: "Abdomen: Guarding present", icon: "🛡️" },
    { label: "Tenderness: None", icon: "✅" },
    { label: "Tenderness: Epigastric", icon: "📍" },
    { label: "Tenderness: Right upper quadrant", icon: "📍" },
    { label: "Tenderness: Left upper quadrant", icon: "📍" },
    { label: "Tenderness: Right lower quadrant", icon: "📍" },
    { label: "Tenderness: Left lower quadrant", icon: "📍" },
    { label: "Tenderness: Periumbilical", icon: "📍" },
    { label: "Tenderness: Suprapubic", icon: "📍" },
    { label: "Liver: Not palpable", icon: "✅" },
    { label: "Liver: Palpable", icon: "🤚" },
    { label: "Liver: Tender", icon: "😖" },
    { label: "Spleen: Not palpable", icon: "✅" },
    { label: "Spleen: Palpable", icon: "🤚" },
    { label: "Kidneys: Not palpable", icon: "✅" },
    { label: "Bowel sounds: Normal", icon: "🔊" },
    { label: "Bowel sounds: Hyperactive", icon: "🔊🔊" },
    { label: "Bowel sounds: Hypoactive", icon: "🔈" },
    { label: "Bowel sounds: Absent", icon: "🔇" },
    { label: "Ascites: Absent", icon: "✅" },
    { label: "Ascites: Present", icon: "💧" },
    { label: "Hernias: None", icon: "✅" },
    { label: "Rectal exam: Normal", icon: "👌" },
    { label: "Rectal exam: Abnormal", icon: "⚠️" },
  ],
  other: [
    { label: "Skin: Normal", icon: "👤" },
    { label: "Skin: Pale", icon: "🏼" },
    { label: "Skin: Jaundiced", icon: "🟡" },
    { label: "Skin: Cyanosed", icon: "🔵" },
    { label: "Skin: Rash present", icon: "🔴" },
    { label: "Lymph nodes: Not palpable", icon: "✅" },
    { label: "Lymph nodes: Palpable", icon: "🤚" },
    { label: "Thyroid: Not palpable", icon: "✅" },
    { label: "Thyroid: Palpable", icon: "🤚" },
    { label: "Thyroid: Enlarged", icon: "🔄" },
    { label: "Musculoskeletal: Normal", icon: "🦴" },
    { label: "Musculoskeletal: Joint swelling", icon: "🦴🔄" },
    { label: "Musculoskeletal: Limited range of motion", icon: "🦴🔒" },
    { label: "Genitourinary: Normal", icon: "👤" },
    { label: "Genitourinary: Abnormal", icon: "⚠️" },
  ],
};
